### ISSUE TITLE
Недоступна команда generate из cli

### ISSUE THREAD

**Issue by otymko** [bia-tech/autodocgen#3]
При установке пакета autodocgen (через opm ставим .ospx) и вызове из cmd:

`autodocgen generate`

Ошибка:

> D:\DATA\Develop\temp\test-docs>autodocgen generate
> {Модуль C:\Program Files (x86)\OneScript\lib\autodocgen\src\Модули\ПараметрыСист
> емы.os / Ошибка в строке: 119 / Ошибка в выражении}

Причины две. 
Первая причина:
`ФайлыКоманд = НайтиФайлы(ОбъединитьПути(ТекущийКаталог(), "src", "Команды"), "*.os");`
Текущий каталог - это каталог, откуда запущен скрипт.
Вторая причина: Когда в цикле перебираются команды стоит условие:
`СтрНачинаетсяС(ФайлКоманды.ИмяБезРасширения, "Команда")`
В итоге это исключает вывод команды СгенерироватьДокументацию.os: 
![image](https://user-images.githubusercontent.com/11651847/41159182-cfc80026-6b55-11e8-9b26-b7139fca4c6b.png)

**Comment by theshadowco** [comment]
По поводу не работает смотрите видео
[record_000004.zip](https://github.com/bia-tech/autodocgen/files/2084498/record_000004.zip)

**Comment by theshadowco** [comment]
По поводу код написан неправильно:

стоит полностью смотреть метод https://github.com/bia-tech/autodocgen/blob/1e27b1ac8f3331cdcbf267c568613cae5bbbc234/src/%D0%9C%D0%BE%D0%B4%D1%83%D0%BB%D0%B8/%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B.os#L123

**Comment by theshadowco** [comment]
И да, схема построения приложения немного отличается от принятой, ибо мне лень делать многие вещи несколько раз и пусть их делает загрузчик

**Comment by khorevaa** [comment]
@theshadowco  Посмотри в сторону [cli](https://github.com/khorevaa/cli) Я там много упростил )в работе

**Comment by theshadowco** [comment]
@khorevaa 
прикольно, я брал за основу официальный шаблон приложения и внес некоторые патчи ибо надо.

**Comment by otymko** [comment]
@theshadowco значит на github не та версия, с которой вы показываете)
![image](https://user-images.githubusercontent.com/11651847/41167378-eac7827c-6b6c-11e8-812f-4988f3acc4f8.png)
