### ISSUE TITLE
Падает при разборе configuration.xml

### ISSUE THREAD

**Issue by 1cgh** [bia-tech/autodocgen#6]
09.06.2018 16:24:37: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files (x86)\OneScript\
lib\autodocgen\src\Классы\РазборСтруктурыКонфигурации1С.os / Ошибка в строке: 57
8 / Неверное значение аргумента}
                                                СвойстваКонфигурации.Вставить(КлючСвойства, ЧтениеXML.Значение);

Падает на 
`			<DefaultRoles>
				<xr:Item xsi:type="xr:MDObjectRef">Role.ПолныеПрава</xr:Item>
				<xr:Item xsi:type="xr:MDObjectRef">Role.АдминистраторСистемы</xr:Item>
				<xr:Item xsi:type="xr:MDObjectRef">Role.ИнтерактивноеОткрытиеВнешнихОтчетовИОбработок</xr:Item>
				<xr:Item xsi:type="xr:MDObjectRef">Role.ПолныеПраваCI</xr:Item>
			</DefaultRoles>
`

**Comment by theshadowco** [comment]
Да, я нашел данную ошибку. 
Релиз с исправлением вот вот выпущу

**Comment by theshadowco** [comment]
Исправлено, проверил на УТ.

Добавил параметр, позволит выполнять публикацию при наличии ошибок (т.е. если часть статей он может создать)
