### ISSUE TITLE
Ошибка в РазборСтруктурыКонфигурации1С.ПрочитатьОписаниеКонстант()

### ISSUE THREAD

**Issue by 1cgh** [bia-tech/autodocgen#7]
```
	Фильтр = Новый Структура("Тип", "Constant");
	
	СтрокиКонстант = ОписаниеКонфигурации.ОбъектыКонфигурации.НайтиСтроки(Фильтр);
```
В configuration.xml в Properties есть узел DefaultConstantsForm
у нас он пустой, например. Т.е.
`<DefaultConstantsForm/>`
соответственно, эта строка подпадает ошибочно под фильтр

**Comment by theshadowco** [comment]
@1cgh 
Таблица ОбъектыКонфигурации содержит объекты конфигурации, свойства туда не добавляются.
